stress_tables:
  urban_suburban: "rBicycleLTS/data/scores/sub _urban_lts.csv"
  rural: "rBicycleLTS/data/scores/rural_bike_lts.csv"

segment:
  forward:
    lanes: ft_lanes
    oneway:
      name: "one_way"
      val: "ft"
    aadt: aadt
    centerline:
      name: "centerline"
      val: TRUE
    speed: speed_limit
    parking:
      name: "ft_park"
      val: TRUE
    width: width
    low_parking:
      name: "low_parking"
      val: TRUE
    bike_infra:
      name: "ft_bike_infra"
      lane: "lane"
      buffered_lane: "buffered_lane"
      track: "track"
      path: "path"
    bike_lane_width: ft_bike_infra_width
  backward:
    lanes: ft_lanes
    oneway:
      name: "one_way"
      val: "ft"
    aadt: aadt
    centerline:
      name: "centerline"
      val: TRUE
    speed: speed_limit
    parking:
      name: "ft_park"
      val: TRUE
    width: width
    low_parking:
      name: "low_parking"
      val: TRUE
    bike_infra:
      name: "ft_bike_infra"
      lane: "lane"
      buffered_lane: "buffered_lane"
      track: "track"
      path: "path"
    bike_lane_width: ft_bike_infra_width

assumptions:
  segment:
    lanes:
      - where: "functional_class IN ('primary','secondary')"
        val: 2
      - where: "functional_class IN ('tertiary')"
        val: 1
      - where: "functional_class IN ('unclassified','residential','living_street')"
        val: 0
      - else: 1
    speed:
      - where: "functional_class IN ('primary','secondary')"
        val: 40
      - where: "functional_class = 'tertiary'"
        val: 30
      - where: "functional_class IN ('unclassified','residential')"
        val: 25
      - where: "functional_class = 'living_street'"
        val: 20
      - else: 30
    width:
      - where: "*"
        val: 50
    parking:
      - where: "*"
        val: True
    low_parking:
      - where: "functional_class IN ('primary','secondary')"
        val: False
      - where: "functional_class = 'tertiary'"
        val: False
      - else: False
    parking_width:
      - where: "*"
        val: 8
    bike_lane_width:
      - where: "*"
        val: 5
    centerline:
      - where: "functional_class IN ('primary','secondary','tertiary')"
        val: True
      - where: "functional_class IN ('unclassified','residential','living_street')"
        val: False
      - else: True
    aadt:
      - where: "functional_class IN ('primary','secondary')"
        val: 20000
      - where: "functional_class = 'tertiary'"
        val: 10000
      - where: "functional_class IN ('unclassified','residential')"
        val: 500
      - where: "functional_class = 'living_street'"
        val: 100
      - else: 20000
