stress_tables:
  urban_suburban: "BicycleLTS/data/scores/sub _urban_lts.csv"
  rural: "BicycleLTS/data/scores/rural_bike_lts.csv"

segment:
    oneway:
      name: "oneway"
      assumptions:
        - where: "df$fclass %in% c('motorway','motorway_link')"
          val: 'Yes'
        - else: 
          val: 'No'
    lanes:
      name: 'lanes'
      assumptions:
        - where: "df$fclass %in% c('residential', 'living_street') & df$oneway %in% c('Yes', 'yes')"
          val: 1
        - where: "df$fclass %in% c('primary','primary_link','secondary','secondary_link')"
          val: 4
        - where: "df$fclass %in% c('tertiary', 'tertiary_link')"
          val: 2
        - where: "df$fclass %in% c('residential','living_street')"
          val: 2
        - where: "df$fclass == 'cycleway'"
          val: 1
        - else: 
          val: 2

    aadt:
      name: 'aadt'
      assumptions:
        - where: "df$fclass %in% c('motorway','motorway_link')"
          val: 16000
        - where: "df$fclass %in% c('primary','primary_link','secondary','secondary_link')"
          val: 16000
        - where: "df$fclass %in% c('tertiary', 'tertiary_link', 'collector')"
          val: 8000
        - where: "df$fclass %in% c('residential')"
          val: 500
        - where: "df$fclass == 'living_street'"
          val: 100
        - where: "df$fclass == 'cycleway'"
          val: 0
        - else: 
          val: 8000
    centerline:
      name: "centerline"
      assumptions:
        - where: "df$fclass %in% c('unclassified','residential','living_street')"
          val: 'No'
        - where: "df$lanes == 1"
          val: 'No'
        - where: "df$fclass == 'cycleway'"
          val: 'No'
        - else:
          val: 'Yes'
    speed:
      name: 'maxspeed'
      assumptions:
        - where: "df$fclass %in% c('primary','primary_link','secondary','secondary_link')"
          val: 40
        - where: "df$fclass %in% c('tertiary', 'tertiary_link')"
          val: 30
        - where: "df$fclass %in% c('unclassified','residential')"
          val: 25
        - where: "df$fclass == 'living_street'"
          val: 20
        - where: "df$fclass == 'cycleway'"
          val: 10
        - else: 
          val: 30
    parking:
      name: "parking"
      assumptions:
        - else: 
          val: 'Yes'
    low_parking:
      name: "low_parking"
      assumptions:
        - where: "df$fclass %in% c('primary','primary_link','secondary','secondary_link')"
          val: 'No'
        - where: "df$fclass %in% c('tertiary', 'tertiary_link')"
          val: 'No'
        - else: 
          val: 'No'
    parking_width:
      name: "p_width"
      assumptions:
        - else: 
          val: 8
    width:
      name: 'width'
      assumptions:
        - else: 
          val: 50.
    bike_lane_width:
      name: 'bike_l_width'
      assumptions:
        - where: "df$fclass == 'cycleway'"
          val: 5
        - else:
          val: 0
    bike_infra:
      name: "fclass"
      vals:
        bike_lane: "lane"
        buffered_bl: "buffered_lane"
        protected_bl: 'protected'
        shared_use_path: "cycleway"

